/// <reference types="expo/types" />

// ─────────────────────────────────────────────────────────────────
// Why this file is tracked in git (NOT in .gitignore):
//
// The triple-slash directive above loads Expo's type declarations,
// which include wildcard module declarations like:
//   declare module '*.css'
//   declare module '*.module.css'
//   declare module '*.module.scss'
//
// Without these, TypeScript 6+ with "moduleResolution": "bundler"
// cannot resolve side-effect imports like:
//   import '@/global.css'
//   import classes from './animated-icon.module.css'
//
// Expo generates this file automatically when you run the dev
// server. By tracking it in git, CI environments also get these
// type declarations, avoiding TS2882 / TS2307 errors.
//
// Do NOT edit this file manually — let Expo manage its content.
// If you need to regenerate it: delete it and run `bun run start`.
// ─────────────────────────────────────────────────────────────────
