name: Deploy Production (API & Mobile)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'

jobs:
  deploy-mobile:
    name: Deploy Mobile
    uses: ./.github/workflows/deploy-mobile.yml
    secrets: inherit

  deploy-api:
    name: Deploy API
    needs: deploy-mobile
    uses: ./.github/workflows/deploy-api-production.yml
    secrets: inherit
