name: 1-PROD Admin

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      skip_tagging:
        description: 'Skip tagging'
        required: false
        type: boolean
        default: false

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy-admin:
    name: Deploy Admin Web Production
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - name: Deploy Admin Production to EAS Hosting
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: make eas-build-admin-production
      - name: Tag deployment
        uses: ./.github/actions/tag-release
        with:
          environment: production
          skip_tagging: ${{ inputs.skip_tagging || 'false' }}
