name: Deploy Admin Production

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy-admin:
    name: Deploy Admin Web Production
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: ./.github/actions/setup
      - name: Deploy Admin Production to EAS Hosting
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: make eas-build-admin-production
